# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  view:
    view_response_listener:
      enabled: true
      force: true
    formats:
      rss: false
      xml: false
      json: true
    failed_validation:    400
    empty_content:        204
    serialize_null:       false
  param_fetcher_listener:  true
  body_listener:
    enabled: true
    default_format: json
    array_normalizer:
      forms: true
  body_converter:
    enabled: true
  exception:
    enabled: true
  format_listener:
    enabled: true
